"""Pydantic models for medical-LLM responses."""

from __future__ import annotations

from pydantic import BaseModel, Field


class LLMDiagnosis(BaseModel):
    """Schema produced by /diagnosis and /exams endpoints."""

    summary: str = Field(..., max_length=800)
    options: list[str] | dict[str, float]

    @classmethod
    def from_llm(cls, text: str) -> 'LLMDiagnosis':
        """Parse a JSON string generated by our medical LLM."""
        cleaned = (
            text.strip().lstrip('```json').lstrip('```').rstrip('```').strip()
        )
        return cls.model_validate_json(cleaned)


__all__ = ['LLMDiagnosis']
