name: sdx
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python >=3.9,<3.13
  - pip
  - poetry
  - nodejs # used by semantic-release
  - tesseract
  - pip:
      # distlib issue
      - paginate==0.5.6
