"""Autogenerated ORM models from Pydantic schemas.

DO NOT EDIT MANUALLY. Regenerate via `python generate_orm_models.py`.
"""

from __future__ import annotations

import datetime
import uuid

from typing import Any, Optional, Union  # noqa

from fhir.resources.fhirtypes import (
    CodeableConceptType,  # noqa
    ReferenceType,  # noqa
)
from public import public
from sqlalchemy import (
    JSON,  # noqa
    Boolean,  # noqa
    Date,  # noqa
    DateTime,  # noqa
    Float,  # noqa
    Integer,  # noqa
    String,  # noqa
    Text,  # noqa
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


@public
class Base(DeclarativeBase):
    """Declarative base for  SDX."""

    pass


@public
class Annotation(Base):
    __tablename__ = 'annotation'

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    language: Mapped[Any] = mapped_column(JSON, index=True)
    fhir_comments: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    extension: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    authorReference: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    authorString: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    authorString__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    text: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    text__ext: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    time: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    time__ext: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)


@public
class ClinicalImpression(Base):
    __tablename__ = 'clinicalimpression'

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    language: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    fhir_comments: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    implicitRules: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    implicitRules__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    language__ext: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    meta: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    contained: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    extension: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    modifierExtension: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    text: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    changePattern: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    date: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    date__ext: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    description: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    description__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    effectiveDateTime: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    effectiveDateTime__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    effectivePeriod: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    encounter: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    finding: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    identifier: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    note: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    performer: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    previous: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    problem: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    prognosisCodeableConcept: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    prognosisReference: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    protocol: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    protocol__ext: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    status: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    status__ext: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    statusReason: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    subject: Mapped[Any] = mapped_column(JSON, index=True)
    summary: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    summary__ext: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    supportingInfo: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )


@public
class Condition(Base):
    __tablename__ = 'condition'

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    language: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    fhir_comments: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    implicitRules: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    implicitRules__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    language__ext: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    meta: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    contained: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    extension: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    modifierExtension: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    text: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    abatementAge: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    abatementDateTime: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    abatementDateTime__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    abatementPeriod: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    abatementRange: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    abatementString: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    abatementString__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    bodySite: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    category: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    clinicalStatus: Mapped[Any] = mapped_column(JSON, index=True)
    code: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    encounter: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    evidence: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    identifier: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    note: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    onsetAge: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    onsetDateTime: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    onsetDateTime__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    onsetPeriod: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    onsetRange: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    onsetString: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    onsetString__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    participant: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    recordedDate: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    recordedDate__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    severity: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    stage: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    subject: Mapped[Any] = mapped_column(JSON, index=True)
    verificationStatus: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )


@public
class Encounter(Base):
    __tablename__ = 'encounter'

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    language: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    fhir_comments: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    implicitRules: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    implicitRules__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    language__ext: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    meta: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    contained: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    extension: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    modifierExtension: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    text: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    account: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    actualPeriod: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    admission: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    appointment: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    basedOn: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    careTeam: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    class_fhir: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    diagnosis: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    dietPreference: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    episodeOfCare: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    identifier: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    length: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    location: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    partOf: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    participant: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    plannedEndDate: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    plannedEndDate__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    plannedStartDate: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    plannedStartDate__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    priority: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    reason: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    serviceProvider: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    serviceType: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    specialArrangement: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    specialCourtesy: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    status: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    status__ext: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    subject: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    subjectStatus: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    type: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    virtualService: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    canonicalEpisodeId: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )


@public
class Observation(Base):
    __tablename__ = 'observation'

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    language: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    fhir_comments: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    implicitRules: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    implicitRules__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    language__ext: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    meta: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    contained: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    extension: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    modifierExtension: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    text: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    basedOn: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    bodySite: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    bodyStructure: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    category: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    code: Mapped[Any] = mapped_column(JSON, index=True)
    component: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    dataAbsentReason: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    derivedFrom: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    device: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    effectiveDateTime: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    effectiveDateTime__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    effectiveInstant: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    effectiveInstant__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    effectivePeriod: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    effectiveTiming: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    encounter: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    focus: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    hasMember: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    identifier: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    instantiatesCanonical: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    instantiatesCanonical__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    instantiatesReference: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    interpretation: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    issued: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    issued__ext: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    method: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    note: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    partOf: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    performer: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    referenceRange: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    specimen: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    status: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    status__ext: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    subject: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    triggeredBy: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    valueAttachment: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    valueBoolean: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    valueBoolean__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    valueCodeableConcept: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    valueDateTime: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    valueDateTime__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    valueInteger: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    valueInteger__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    valuePeriod: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    valueQuantity: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    valueRange: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    valueRatio: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    valueReference: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    valueSampledData: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    valueString: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    valueString__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    valueTime: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    valueTime__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )


@public
class Patient(Base):
    __tablename__ = 'patient'

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    language: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    fhir_comments: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    implicitRules: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    implicitRules__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    language__ext: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    meta: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    contained: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    extension: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    modifierExtension: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    text: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    active: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    active__ext: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    address: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    birthDate: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    birthDate__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    communication: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    contact: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    deceasedBoolean: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    deceasedBoolean__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    deceasedDateTime: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    deceasedDateTime__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    gender: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    gender__ext: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    generalPractitioner: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    identifier: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    link: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    managingOrganization: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    maritalStatus: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    multipleBirthBoolean: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    multipleBirthBoolean__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    multipleBirthInteger: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    multipleBirthInteger__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    name: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    photo: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    telecom: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)


@public
class Procedure(Base):
    __tablename__ = 'procedure'

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    language: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    fhir_comments: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    implicitRules: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    implicitRules__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    language__ext: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    meta: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    contained: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    extension: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    modifierExtension: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    text: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    basedOn: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    bodySite: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    category: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    code: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    complication: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    encounter: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    focalDevice: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    focus: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    followUp: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    identifier: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    instantiatesCanonical: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    instantiatesCanonical__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    instantiatesUri: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    instantiatesUri__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    location: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    note: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    occurrenceAge: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    occurrenceDateTime: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    occurrenceDateTime__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    occurrencePeriod: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    occurrenceRange: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    occurrenceString: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    occurrenceString__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    occurrenceTiming: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    outcome: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    partOf: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    performer: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    reason: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    recorded: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    recorded__ext: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    recorder: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    report: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    reportedBoolean: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    reportedBoolean__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    reportedReference: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    status: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    status__ext: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    statusReason: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    subject: Mapped[Any] = mapped_column(JSON, index=True)
    supportingInfo: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True
    )
    used: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)


@public
class AIOutput(Base):
    __tablename__ = 'aioutput'

    language: Mapped[Any] = mapped_column(JSON, index=True)
    id: Mapped[str] = mapped_column(String, primary_key=True)
    encounter_id: Mapped[str] = mapped_column(String, index=True)
    type: Mapped[Any] = mapped_column(JSON, index=True)
    content: Mapped[str] = mapped_column(String, index=True)
    model_version: Mapped[str] = mapped_column(String, index=True)
    timestamp: Mapped[datetime] = mapped_column(DateTime, index=True)


@public
class DeIdentifiedDatasetDescriptor(Base):
    __tablename__ = 'deidentifieddatasetdescriptor'

    language: Mapped[Any] = mapped_column(JSON, index=True)
    dataset_id: Mapped[str] = mapped_column(String, index=True)
    generation_date: Mapped[datetime] = mapped_column(DateTime, index=True)
    version: Mapped[str] = mapped_column(String, index=True)
    records: Mapped[int] = mapped_column(Integer, index=True)
    license: Mapped[str] = mapped_column(String, index=True)
    url: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)


@public
class Evaluation(Base):
    __tablename__ = 'evaluation'

    language: Mapped[Any] = mapped_column(JSON, index=True)
    id: Mapped[str] = mapped_column(String, primary_key=True)
    aioutput_id: Mapped[str] = mapped_column(String, index=True)
    output_type: Mapped[Any] = mapped_column(JSON, index=True)
    ratings: Mapped[Any] = mapped_column(JSON, index=True)
    safety: Mapped[Any] = mapped_column(JSON, index=True)
    comments: Mapped[Any] = mapped_column(JSON, nullable=True, index=True)
    timestamp: Mapped[datetime] = mapped_column(DateTime, index=True)
