"""Autogenerated SQLModel tables from Pydantic schemas.

DO NOT EDIT MANUALLY:
    regenerate via `python scripts/gen_models/gen_sqlmodel.py`.
"""

from __future__ import annotations

import uuid

from typing import Any, Optional

from public import public
from sqlalchemy import (
    JSON,
    Boolean,
    Date,
    DateTime,
    Float,
    Integer,
    String,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlmodel import Field, SQLModel


@public
class Annotation(SQLModel, table=True):
    __tablename__: str = 'annotation'

    id: str | None = Field(
        default_factory=lambda: str(uuid.uuid4()),
        primary_key=True,
        sa_type=String(36),
    )
    language: Optional = Field(
        ...,
        primary_key=False,
        nullable=False,
        index=True,
        sa_type=JSONB,
    )
    fhir_comments: Union = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    extension: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    authorReference: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    authorString: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    authorString__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    text: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    text__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    time: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    time__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )


@public
class ClinicalImpression(SQLModel, table=True):
    __tablename__: str = 'clinicalimpression'

    id: str | None = Field(
        default_factory=lambda: str(uuid.uuid4()),
        primary_key=True,
        sa_type=String(36),
    )
    language: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    fhir_comments: Union = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    implicitRules: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    implicitRules__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    language__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    meta: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    contained: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    extension: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    modifierExtension: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    text: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    changePattern: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    date: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    date__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    description: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    description__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    effectiveDateTime: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    effectiveDateTime__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    effectivePeriod: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    encounter: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    finding: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    identifier: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    note: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    performer: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    previous: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    problem: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    prognosisCodeableConcept: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    prognosisReference: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    protocol: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    protocol__ext: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    status: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    status__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    statusReason: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    subject: ReferenceType = Field(
        ...,
        primary_key=False,
        nullable=False,
        index=True,
        sa_type=JSONB,
    )
    summary: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    summary__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    supportingInfo: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )


@public
class Condition(SQLModel, table=True):
    __tablename__: str = 'condition'

    id: str | None = Field(
        default_factory=lambda: str(uuid.uuid4()),
        primary_key=True,
        sa_type=String(36),
    )
    language: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    fhir_comments: Union = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    implicitRules: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    implicitRules__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    language__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    meta: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    contained: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    extension: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    modifierExtension: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    text: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    abatementAge: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    abatementDateTime: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    abatementDateTime__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    abatementPeriod: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    abatementRange: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    abatementString: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    abatementString__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    bodySite: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    category: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    clinicalStatus: CodeableConceptType = Field(
        ...,
        primary_key=False,
        nullable=False,
        index=True,
        sa_type=JSONB,
    )
    code: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    encounter: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    evidence: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    identifier: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    note: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    onsetAge: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    onsetDateTime: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    onsetDateTime__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    onsetPeriod: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    onsetRange: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    onsetString: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    onsetString__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    participant: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    recordedDate: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    recordedDate__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    severity: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    stage: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    subject: ReferenceType = Field(
        ...,
        primary_key=False,
        nullable=False,
        index=True,
        sa_type=JSONB,
    )
    verificationStatus: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )


@public
class Encounter(SQLModel, table=True):
    __tablename__: str = 'encounter'

    id: str | None = Field(
        default_factory=lambda: str(uuid.uuid4()),
        primary_key=True,
        sa_type=String(36),
    )
    language: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    fhir_comments: Union = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    implicitRules: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    implicitRules__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    language__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    meta: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    contained: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    extension: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    modifierExtension: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    text: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    account: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    actualPeriod: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    admission: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    appointment: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    basedOn: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    careTeam: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    class_fhir: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    diagnosis: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    dietPreference: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    episodeOfCare: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    identifier: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    length: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    location: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    partOf: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    participant: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    plannedEndDate: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    plannedEndDate__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    plannedStartDate: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    plannedStartDate__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    priority: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    reason: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    serviceProvider: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    serviceType: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    specialArrangement: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    specialCourtesy: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    status: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    status__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    subject: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    subjectStatus: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    type: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    virtualService: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    canonicalEpisodeId: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )


@public
class Observation(SQLModel, table=True):
    __tablename__: str = 'observation'

    id: str | None = Field(
        default_factory=lambda: str(uuid.uuid4()),
        primary_key=True,
        sa_type=String(36),
    )
    language: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    fhir_comments: Union = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    implicitRules: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    implicitRules__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    language__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    meta: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    contained: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    extension: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    modifierExtension: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    text: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    basedOn: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    bodySite: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    bodyStructure: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    category: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    code: CodeableConceptType = Field(
        ...,
        primary_key=False,
        nullable=False,
        index=True,
        sa_type=JSONB,
    )
    component: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    dataAbsentReason: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    derivedFrom: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    device: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    effectiveDateTime: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    effectiveDateTime__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    effectiveInstant: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    effectiveInstant__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    effectivePeriod: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    effectiveTiming: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    encounter: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    focus: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    hasMember: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    identifier: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    instantiatesCanonical: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    instantiatesCanonical__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    instantiatesReference: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    interpretation: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    issued: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    issued__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    method: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    note: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    partOf: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    performer: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    referenceRange: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    specimen: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    status: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    status__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    subject: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    triggeredBy: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    valueAttachment: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    valueBoolean: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    valueBoolean__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    valueCodeableConcept: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    valueDateTime: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    valueDateTime__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    valueInteger: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    valueInteger__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    valuePeriod: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    valueQuantity: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    valueRange: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    valueRatio: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    valueReference: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    valueSampledData: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    valueString: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    valueString__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    valueTime: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    valueTime__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )


@public
class Patient(SQLModel, table=True):
    __tablename__: str = 'patient'

    id: str | None = Field(
        default_factory=lambda: str(uuid.uuid4()),
        primary_key=True,
        sa_type=String(36),
    )
    language: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    fhir_comments: Union = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    implicitRules: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    implicitRules__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    language__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    meta: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    contained: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    extension: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    modifierExtension: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    text: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    active: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    active__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    address: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    birthDate: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    birthDate__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    communication: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    contact: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    deceasedBoolean: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    deceasedBoolean__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    deceasedDateTime: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    deceasedDateTime__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    gender: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    gender__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    generalPractitioner: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    identifier: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    link: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    managingOrganization: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    maritalStatus: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    multipleBirthBoolean: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    multipleBirthBoolean__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    multipleBirthInteger: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    multipleBirthInteger__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    name: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    photo: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    telecom: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )


@public
class Procedure(SQLModel, table=True):
    __tablename__: str = 'procedure'

    id: str | None = Field(
        default_factory=lambda: str(uuid.uuid4()),
        primary_key=True,
        sa_type=String(36),
    )
    language: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    fhir_comments: Union = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    implicitRules: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    implicitRules__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    language__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    meta: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    contained: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    extension: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    modifierExtension: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    text: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    basedOn: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    bodySite: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    category: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    code: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    complication: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    encounter: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    focalDevice: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    focus: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    followUp: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    identifier: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    instantiatesCanonical: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    instantiatesCanonical__ext: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    instantiatesUri: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    instantiatesUri__ext: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    location: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    note: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    occurrenceAge: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    occurrenceDateTime: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    occurrenceDateTime__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    occurrencePeriod: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    occurrenceRange: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    occurrenceString: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    occurrenceString__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    occurrenceTiming: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    outcome: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    partOf: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    performer: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    reason: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    recorded: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    recorded__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    recorder: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    report: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    reportedBoolean: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    reportedBoolean__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    reportedReference: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    status: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    status__ext: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    statusReason: Any = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    subject: ReferenceType = Field(
        ...,
        primary_key=False,
        nullable=False,
        index=True,
        sa_type=JSONB,
    )
    supportingInfo: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    used: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )


@public
class AIOutput(SQLModel, table=True):
    __tablename__: str = 'aioutput'

    language: Optional = Field(
        ...,
        primary_key=False,
        nullable=False,
        index=True,
        sa_type=JSONB,
    )
    id: str = Field(
        ...,
        primary_key=True,
        nullable=False,
        index=False,
        sa_type=String,
    )
    encounter_id: str = Field(
        ...,
        primary_key=False,
        nullable=False,
        index=True,
        sa_type=String,
    )
    type: Literal = Field(
        ...,
        primary_key=False,
        nullable=False,
        index=True,
        sa_type=JSONB,
    )
    content: str = Field(
        ...,
        primary_key=False,
        nullable=False,
        index=True,
        sa_type=String,
    )
    model_version: str = Field(
        ...,
        primary_key=False,
        nullable=False,
        index=True,
        sa_type=String,
    )
    timestamp: datetime = Field(
        ...,
        primary_key=False,
        nullable=False,
        index=True,
        sa_type=DateTime,
    )


@public
class DeIdentifiedDatasetDescriptor(SQLModel, table=True):
    __tablename__: str = 'deidentifieddatasetdescriptor'

    language: Optional = Field(
        ...,
        primary_key=False,
        nullable=False,
        index=True,
        sa_type=JSONB,
    )
    dataset_id: str = Field(
        ...,
        primary_key=False,
        nullable=False,
        index=True,
        sa_type=String,
    )
    generation_date: datetime = Field(
        ...,
        primary_key=False,
        nullable=False,
        index=True,
        sa_type=DateTime,
    )
    version: str = Field(
        ...,
        primary_key=False,
        nullable=False,
        index=True,
        sa_type=String,
    )
    records: int = Field(
        ...,
        primary_key=False,
        nullable=False,
        index=True,
        sa_type=Integer,
    )
    license: str = Field(
        ...,
        primary_key=False,
        nullable=False,
        index=True,
        sa_type=String,
    )
    url: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )


@public
class Evaluation(SQLModel, table=True):
    __tablename__: str = 'evaluation'

    language: Optional = Field(
        ...,
        primary_key=False,
        nullable=False,
        index=True,
        sa_type=JSONB,
    )
    id: str = Field(
        ...,
        primary_key=True,
        nullable=False,
        index=False,
        sa_type=String,
    )
    aioutput_id: str = Field(
        ...,
        primary_key=False,
        nullable=False,
        index=True,
        sa_type=String,
    )
    output_type: Literal = Field(
        ...,
        primary_key=False,
        nullable=False,
        index=True,
        sa_type=JSONB,
    )
    ratings: Dict = Field(
        ...,
        primary_key=False,
        nullable=False,
        index=True,
        sa_type=JSONB,
    )
    safety: Literal = Field(
        ...,
        primary_key=False,
        nullable=False,
        index=True,
        sa_type=JSONB,
    )
    comments: Optional = Field(
        None,
        primary_key=False,
        nullable=True,
        index=True,
        sa_type=JSONB,
    )
    timestamp: datetime = Field(
        ...,
        primary_key=False,
        nullable=False,
        index=True,
        sa_type=DateTime,
    )
